compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  #image_family: freebsd-12-1
  image: family/freebsd-13-0
  platform: FreeBSD
  cpu: 1
  disk: 40

task:
  install_script:
    - pkg install -y py38-oci
  test_script:
    - sysctl kern.geom.conftxt
    - camcontrol devlist
    - gpart show
    - df -h
    - gpart resize -i 3 /dev/da0
    - gpart show
    - growfs -y /dev/gpt/rootfs
    - df -h
