env:
  CIRRUS_CLONE_DEPTH: 1
  SECRET_VAR: ENCRYPTED[d4804efa4c3adc71c2a77948105a81d3c6c7edfca77294eb0209e7945ce160154a1846d89477d7d142a1d8d38155a517]

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    - pkg install -y autoconf automake awscli
  create_user_script: pw useradd git
  ci_script: su git ./ci-script.sh
  artifact_script: su git ./artifact-script.sh
