freebsd_instance:
  image_project: freebsd-org-cloud-dev
  image_family: freebsd-12-1
  platform: FreeBSD
  cpu: 1
  disk: 40

task:
  test_script:
    - sysctl kern.geom.conftxt
    - camcontrol devlist
    - gpart show
    - df -h
    - gpart resize -i 3 /dev/da0
    - growfs -y /dev/gpt/rootfs
    - df -h
